name: Deploy SAM Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (dev or prod)'
        required: true
        default: 'dev'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Java 21
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      # Build the Java application
      - name: Build with Maven
        run: mvn clean package

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  

      # Build SAM application
      - name: SAM Build
        run: sam build

      # Deploy SAM application
      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name s3-eda-${{ github.event.inputs.environment || 'dev' }} \
            --parameter-overrides \
              Environment=${{ github.event.inputs.environment || 'dev' }} \
              EmailAddress=${{ secrets.EMAIL_ADDRESS }} \
            --region eu-central-1 \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM
